### ISSUE TITLE
I should using GPU, bur ERROR

### ISSUE THREAD

**Issue by SangWoonJeong** [LiamMaclean216/Pytorch-Transfomer#4]
I using GPU, so model.cuda()
and train.cuda()

but, this error

Traceback (most recent call last):
  File "/home/woon/anaconda3/envs/pytorch/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3417, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-5-6f05d5b76451>", line 10, in <module>
    train_predict_outputs = model(train_data)
  File "/home/woon/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/woon/06_pytorch/Reference_code_/Pytorch-Transfomer-master/Network.py", line 74, in forward
    e = self.encs[0](self.pos(self.enc_input_fc(x)))
  File "/home/woon/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/woon/06_pytorch/Reference_code_/Pytorch-Transfomer-master/Network.py", line 19, in forward
    a = self.attn(x)
  File "/home/woon/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/woon/06_pytorch/Reference_code_/Pytorch-Transfomer-master/utils.py", line 50, in forward
    a.append(h(x, kv = kv))
  File "/home/woon/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/woon/06_pytorch/Reference_code_/Pytorch-Transfomer-master/utils.py", line 30, in forward
    return attention(self.query(x), self.key(x), self.value(x))
  File "/home/woon/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/woon/06_pytorch/Reference_code_/Pytorch-Transfomer-master/utils.py", line 97, in forward
    x = self.fc1(x)
  File "/home/woon/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/woon/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 87, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/woon/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py", line 1612, in linear
    output = input.matmul(weight.t())
RuntimeError: Expected object of device type cuda but got device type cpu for argument #2 'mat2' in call to _th_mm

Change the network ??

**Comment by KK-xi** [comment]
> I using GPU, so model.cuda()
> and train.cuda()
> 
> but, this error
> 
> Traceback (most recent call last):
> File "/home/woon/anaconda3/envs/pytorch/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3417, in run_code
> exec(code_obj, self.user_global_ns, self.user_ns)
> File "", line 10, in
> train_predict_outputs = model(train_data)
> File "/home/woon/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in **call**
> result = self.forward(*input, **kwargs)
> File "/home/woon/06_pytorch/Reference_code_/Pytorch-Transfomer-master/Network.py", line 74, in forward
> e = self.encs[0](self.pos(self.enc_input_fc(x)))
> File "/home/woon/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in **call**
> result = self.forward(*input, **kwargs)
> File "/home/woon/06_pytorch/Reference_code_/Pytorch-Transfomer-master/Network.py", line 19, in forward
> a = self.attn(x)
> File "/home/woon/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in **call**
> result = self.forward(*input, **kwargs)
> File "/home/woon/06_pytorch/Reference_code_/Pytorch-Transfomer-master/utils.py", line 50, in forward
> a.append(h(x, kv = kv))
> File "/home/woon/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in **call**
> result = self.forward(*input, **kwargs)
> File "/home/woon/06_pytorch/Reference_code_/Pytorch-Transfomer-master/utils.py", line 30, in forward
> return attention(self.query(x), self.key(x), self.value(x))
> File "/home/woon/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in **call**
> result = self.forward(*input, **kwargs)
> File "/home/woon/06_pytorch/Reference_code_/Pytorch-Transfomer-master/utils.py", line 97, in forward
> x = self.fc1(x)
> File "/home/woon/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in **call**
> result = self.forward(*input, **kwargs)
> File "/home/woon/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 87, in forward
> return F.linear(input, self.weight, self.bias)
> File "/home/woon/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py", line 1612, in linear
> output = input.matmul(weight.t())
> RuntimeError: Expected object of device type cuda but got device type cpu for argument #2 'mat2' in call to _th_mm
> 
> Change the network ??

When defining Transformer in the Network.py file, you need to change self.encs=[] to self.encs=nn.ModuleList([]), I solved this problem by this way.
